新增 支持泛域名解析，支持一次设置多个七牛cdn域名
daozzg/qiniu-cdn-ssl-autoupdate pull request #2
Opened 2018-10-10 08:29 UTC by YahuiWong

2018-12-02 01:44 UTC, zgfh commented
请先解决冲突

2018-12-02 13:24 UTC, zgfh requested changes
非常感谢您的PR，个人感觉同时更新多个七牛CDN证书是非常有用的功能，但有一些问题还是辛苦您能改一下，
1. 泛域名已经支持，见：https://github.com/daozzg/qiniu-cdn-ssl-autoupdate/pull/1/files， 个人感觉通过用户指定 "*.xx.xx" 可能更通用
2. 考虑到我自己和其他用户已经在使用，建议扩展最好向下兼容，DOMAIN 变量最好不改名称，我的建议：可以增加CDNDOMAINS变量，默认值为DOMAIN，如果用户指定了多个，在进行多个处理，你觉得呢？

2018-12-02 13:24 UTC, zgfh commented on ReadMe.md
> +git clone https://github.com/YahuiWong/qiniu-cdn-ssl-autoupdate.git
非常感谢您的PR，但文档中的daozzg都被改成YahuiWong 感觉不太合适，可否优化下？

2018-12-03 13:16 UTC, YahuiWong commented on ReadMe.md
> +git clone https://github.com/YahuiWong/qiniu-cdn-ssl-autoupdate.git
这个没关系的，合并过之后可以自行修改

2018-12-03 13:20 UTC, YahuiWong commented
单域名是泛域名的子集 不考虑兼容之前的形式，

2018-12-13 09:12 UTC, closed without merging